apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-scheduler-plugin-sa
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-scheduler-plugin-clusterrolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: metrics-scheduler-plugin-sa
    namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: "/etc/kubernetes/scheduler.conf"
    leaderElection:
      leaderElect: false
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
    profiles:
      - schedulerName: metrics-scheduler
        plugins:
          score:
            enabled:
              - name: metrics-scheduler-plugin
                weight: 1
            disabled:
              - name: NodePreferAvoidPods
---
# 4. 部署自定义插件（Deployment方式）
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-scheduler-plugin
  namespace: kube-system
  labels:
    component: metrics-scheduler-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metrics-scheduler-plugin
  template:
    metadata:
      labels:
        component: metrics-scheduler-plugin
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: u-33
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccount: metrics-scheduler-plugin-sa
      # 要将 Pod 标记为关键性（critical），设置 Pod 的 priorityClassName 为 system-cluster-critical 或者 system-node-critical。
      # system-node-critical 是最高级别的可用性优先级，甚至比 system-cluster-critical 更高。
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
        - hostPath:
            path: /etc/kubernetes/scheduler.conf
            type: File
          name: kubeconfig
      containers:
        - name: scheduler-ctrl
          image: s7799653/metrics-scheduler-plugin:v1.21.1
          imagePullPolicy: Always
          args:
            - metrics-scheduler-plugin
            - --leader-elect=false
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
            - --secure-port=10260
          env:
            - name: MEMORY_WEIGHT
              value: "5"
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes/scheduler-config.yaml
              subPath: scheduler-config.yaml
              readOnly: true
            - mountPath: /etc/kubernetes/scheduler.conf
              name: kubeconfig
              readOnly: true